Repository Products-Squad/products, pull requests merged in 2019-11, with the labels that each got.

#89 Update README.md
  README.md
Labels: enhancement

#87 Update Vagrantfile for IBM command-line
  .gitignore
  Vagrantfile
Labels: technical debt

#91 Add honcho for managing Procfile
  requirements.txt
Labels: enhancement

#92 Change config file to serve third party db
  manifest.yml
Labels: technical debt

#93 Define ElephantSQL as a User Provided Services in Cloud Foundry [T#82]
  manifest.yml
  service/__init__.py
Labels: technical debt

#121 Add codecov config
  codecov.yml
Labels: enhancement

#119 Setup BDD Configuration
  Vagrantfile
  features/environment.py
  features/products.feature
  features/steps/steps.py
  requirements.txt
  service/model.py
  service/service.py
  setup.cfg
  tests/test_service.py
Labels: enhancement

#142 Require API authentication by giving an API Key [E#124]
  service/__init__.py
  service/service.py
  tests/test_service.py
Labels: enhancement

#144 Revised webpage and BDD for API Key [E#124]
  features/environment.py
  features/products.feature
  features/steps/steps.py
  service/service.py
  service/static/index.html
  service/static/js/rest_api.js
Labels: enhancement

#154 Pass API key through js
  features/environment.py
  features/products.feature
  features/steps/steps.py
  service/service.py
  service/static/index.html
  service/static/js/rest_api.js
Labels: bug
